import React, { useState, useEffect, useRef } from 'react';
import './AICoach.css';

const AICoach = () => {
  const [messages, setMessages] = useState([
    {
      type: 'ai',
      content: `Hello! 👋 I'm your personal AI fitness coach, and I'm excited to help you on your fitness journey! 

I can assist you with:
• 🏋️ Personalized workout plans
• 🥗 Nutrition guidance and meal planning  
• 📈 Progress tracking and motivation
• 💪 Form tips and exercise modifications
• 🎯 Goal setting and achievement strategies

What would you like to work on today? Feel free to ask me anything about fitness, health, or wellness!`
    }
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const chatContainerRef = useRef(null);

  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [messages]);

  const sendMessage = async () => {
    if (isLoading || !inputMessage.trim()) return;

    const userMessage = inputMessage.trim();
    setInputMessage('');
    setIsLoading(true);

    // Add user message
    setMessages(prev => [...prev, { type: 'user', content: userMessage }]);

    try {
      const response = await fetch('/api/ai-chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: userMessage })
      });

      const data = await response.json();

      if (data.success) {
        setMessages(prev => [...prev, { type: 'ai', content: data.response }]);
      } else {
        setMessages(prev => [...prev, { 
          type: 'ai', 
          content: data.fallback || 'Sorry, I had trouble processing that. Can you try rephrasing your question?' 
        }]);
      }
    } catch (error) {
      console.error('Chat error:', error);
      setMessages(prev => [...prev, { 
        type: 'ai', 
        content: "I'm here to help with your fitness journey! I can assist with workouts, nutrition advice, motivation, and tracking your progress. What would you like to know?" 
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const generateWorkoutPlan = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('/api/ai-workout-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          preferences: {
            timeAvailable: 30,
            fitnessLevel: 'intermediate',
            equipment: ['bodyweight'],
            intensity: 'moderate'
          }
        })
      });

      const data = await response.json();

      if (data.success) {
        const workoutMessage = {
          type: 'ai',
          content: `🏋️ ${data.workoutPlan.title}

**Description:** ${data.workoutPlan.description}

${data.workoutPlan.content}

*Generated by: ${data.generatedBy} at ${new Date(data.timestamp).toLocaleString()}*`
        };
        setMessages(prev => [...prev, workoutMessage]);
      } else {
        alert('Failed to generate workout plan: ' + data.error);
      }
    } catch (error) {
      console.error('Workout generation error:', error);
      alert('Failed to generate workout plan. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const openFormCorrection = () => {
    alert('Form correction feature would open camera interface for exercise analysis');
  };

  const openVirtualTraining = () => {
    alert('Virtual training would connect you with certified personal trainers');
  };

  const features = [
    {
      icon: 'fas fa-dumbbell',
      title: 'Personalized Workouts',
      description: 'Get custom workout plans tailored to your fitness level, goals, and available equipment.'
    },
    {
      icon: 'fas fa-utensils',
      title: 'Nutrition Guidance',
      description: 'Receive meal plans and nutritional advice based on your dietary preferences and goals.'
    },
    {
      icon: 'fas fa-chart-line',
      title: 'Progress Analysis',
      description: 'Get insights into your workout performance and suggestions for improvement.'
    },
    {
      icon: 'fas fa-calendar-alt',
      title: 'Schedule Optimization',
      description: 'Automatically adjust your workout schedule based on your availability and recovery needs.'
    },
    {
      icon: 'fas fa-video',
      title: 'Form Correction',
      description: 'Upload videos of your exercises for AI-powered form analysis and corrections.'
    },
    {
      icon: 'fas fa-trophy',
      title: 'Goal Setting',
      description: 'Set and track SMART fitness goals with the AI\'s guidance and motivation.'
    }
  ];

  return (
    <div className="ai-coach-page">
      <div className="dashboard-container">
        {/* Sidebar */}
        <div className="sidebar">
          <div className="sidebar-header">
            <img src="https://ui-avatars.com/api/?name=User&background=6C63FF&color=fff" alt="Profile" />
            <div>
              <h3 className="user-name">User</h3>
              <div className="user-plan">Free Plan</div>
            </div>
          </div>
          
          <ul className="nav-menu">
            <li className="nav-item">
              <a href="/dashboard" className="nav-link">
                <i className="fas fa-tachometer-alt"></i> Dashboard
              </a>
            </li>
            <li className="nav-item">
              <a href="/workouts" className="nav-link">
                <i className="fas fa-dumbbell"></i> Workouts
              </a>
            </li>
            <li className="nav-item">
              <a href="/nutrition" className="nav-link">
                <i className="fas fa-utensils"></i> Nutrition
              </a>
            </li>
            <li className="nav-item">
              <a href="/ai-coach" className="nav-link active">
                <i className="fas fa-robot"></i> AI Coach
              </a>
            </li>
          </ul>
        </div>

        {/* Main Content */}
        <div className="main-content">
          <div className="page-header">
            <h1 className="page-title">AI Fitness Coach</h1>
            <div>
              <button className="btn btn-primary" onClick={generateWorkoutPlan} disabled={isLoading}>
                <i className="fas fa-magic"></i> Generate Workout Plan
              </button>
              <button className="btn btn-primary" onClick={openFormCorrection} style={{marginLeft: '10px'}}>
                <i className="fas fa-video"></i> Form Correction
              </button>
              <button className="btn btn-primary" onClick={openVirtualTraining} style={{marginLeft: '10px'}}>
                <i className="fas fa-user-tie"></i> Virtual Training
              </button>
            </div>
          </div>
          
          <div className="ai-coach-card">
            <div className="card-header">
              <h2 className="card-title">Chat with your AI Coach</h2>
            </div>
            
            <div className="chat-container" ref={chatContainerRef}>
              {messages.map((message, index) => (
                <div key={index} className={`${message.type}-message`}>
                  <strong>{message.type === 'ai' ? 'AI Coach:' : 'You:'}</strong>
                  <p style={{whiteSpace: 'pre-wrap'}}>{message.content}</p>
                </div>
              ))}
              {isLoading && (
                <div className="ai-message">
                  <strong>AI Coach:</strong>
                  <p><i className="fas fa-spinner fa-spin"></i> Thinking...</p>
                </div>
              )}
            </div>
            
            <div className="input-group">
              <input 
                type="text" 
                className="form-control" 
                placeholder="Ask your AI coach anything..."
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                onKeyPress={handleKeyPress}
                disabled={isLoading}
              />
              <button 
                className="btn btn-primary" 
                onClick={sendMessage}
                disabled={isLoading || !inputMessage.trim()}
              >
                {isLoading ? (
                  <><i className="fas fa-spinner fa-spin"></i> Sending</>
                ) : (
                  <><i className="fas fa-paper-plane"></i> Send</>
                )}
              </button>
            </div>
          </div>
          
          <div className="ai-coach-card">
            <div className="card-header">
              <h2 className="card-title">AI Coach Features</h2>
            </div>
            
            <div className="coach-features">
              {features.map((feature, index) => (
                <div key={index} className="feature-card">
                  <div className="feature-icon">
                    <i className={feature.icon}></i>
                  </div>
                  <h3 className="feature-title">{feature.title}</h3>
                  <p className="feature-desc">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AICoach;